application: helloword-154502
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_gh/.*
  script: gae.py
  secure: optional

- url: /favicon.ico
  script: gae.py
  secure: optional

- url: /.*
  script: legacy.py
  secure: optional

libraries:
- name: pycrypto
  version: "latest"
